# 设备类型: gateway(网关设备)
device_type: "gateway"

mqtt:
  broker: "47.92.253.145:1883"
  client_id: "gateway_client_001"
  username: "gateway-001"
  password: "gateway-001"
  qos: 1
  clean_session: true
  keep_alive: 60

# 网关设备信息
device:
  device_id: "aad473a5-b26a-9c69-a197-60fee95a3cda"
  device_number: "device_number_666666"

# 网关拓扑结构
gateway:
  # 直连子设备列表
  sub_devices:
    - sub_device_number: "sub_666666"
      device_id: "f2d11a27-6bd9-c9ea-f4bd-f11984a4a575"
      description: "传感器"

  # 子网关列表
  sub_gateways:
    - sub_gateway_number: "sub_gateway_666666"
      device_id: "46f174af-6a34-3af0-b543-b476fb77f6b9"
      description: "边缘网关"
      # 子网关下的子设备
      sub_devices:
        - sub_device_number: "sub_sub_666666"
          device_id: "b4c321a5-02ec-7996-7f61-1ef784bef977"
          description: "子网关下的传感器"

database:
  host: "47.92.253.145"
  port: 5432
  dbname: "ThingsPanel"
  username: "postgres"
  password: "postgresThingsPanel"
  sslmode: "disable"
  max_open_conns: 10
  max_idle_conns: 5

api:
  base_url: "http://47.92.253.145:9999"
  api_key: "sk_6991d099ba736d989263e294b639b9c795b04284a19d89f7ae75d0fcf87c3770"
  timeout: 30

test:
  wait_db_sync_seconds: 3
  wait_mqtt_response_seconds: 5
  retry_times: 3
  log_level: "debug"
