# ThingsPanel Docker 镜像自动构建工作流
# 
# 功能说明:
# 1. 自动构建 Docker 镜像并推送到三个镜像仓库:
#    - DockerHub (thingspanel/thingspanel-go)
#    - GitHub Container Registry (ghcr.io)
#    - 极狐容器镜像仓库 (registry.jihulab.com)
#
# 触发方式:
# - Release触发: 当创建或更新 Release 时自动触发构建
# - 手动触发: 可以通过 GitHub Actions 页面手动触发
#
# 版本号处理:
# - 通过 Release 触发: 使用 Release 的 tag 名称作为版本号 (例如: v1.1.4)
# - 手动触发: 使用最新的 tag 作为版本号
# - 无 tag 时: 使用 'latest' 作为版本号
#
# 必需的 Secrets:
# - DOCKERHUB_USERNAME: DockerHub 用户名
# - DOCKERHUB_TOKEN: DockerHub 访问令牌
# - GITHUB_TOKEN: GitHub 访问令牌 (自动提供)
# - JH_USER: 极狐仓库用户名
# - JH_PASS: 极狐仓库密码

name: docker镜像构建-自动版本
on:
  release:
    types: [published, edited]  # 创建或更新 Release 时触发
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 获取版本号
        id: get_version
        run: |
          if [[ $GITHUB_EVENT_NAME == 'release' ]]; then
            # 从 release 获取版本号
            VERSION=${{ github.event.release.tag_name }}
          else
            # 获取最新的 tag 作为版本号
            VERSION=$(git describe --tags --abbrev=0 2>/dev/null || echo 'latest')
          fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: 设置小写用户名
        run: |
          echo "OWNER_LC=${GITHUB_REPOSITORY_OWNER,,}" >> ${GITHUB_ENV}

      - name: 登录 DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 登录 GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 登录极狐镜像仓库
        uses: docker/login-action@v2
        with:
          registry: registry.jihulab.com
          username: ${{ secrets.JH_USER }}
          password: ${{ secrets.JH_PASS }}

      - name: 设置 Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: 构建并推送镜像
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            thingspanel/thingspanel-go:${{ env.VERSION }}
            ghcr.io/${{ env.OWNER_LC }}/thingspanel-go:${{ env.VERSION }}
            registry.jihulab.com/thingspanel/docker-images/thingspanel-go:${{ env.VERSION }}
          labels: |
            org.opencontainers.image.title=thingspanel-go
            org.opencontainers.image.description=thingspanel-go
            org.opencontainers.image.version=${{ env.VERSION }}